### ISSUE TITLE
Operation not permitted in IOS

### ISSUE THREAD

**Issue by ghost** [Tkko/flutter_smart_auth#10]
**Describe the bug**
Cannot open file '/Users/username/Documents/src/flutter/bin/cache/artifacts/engine/ios/Flutter.xcframework/ios-arm64_x86_64-simulator/Flutter.framework/Modules/module.modulemap': Operation not permitted

**Comment by Tkko** [comment]
Hey @VasuBhav, which Flutter version are you using? and when exactly is this issue happening?

**Comment by Tkko** [comment]
The fake support for iOS is fully removed.
