### ISSUE TITLE
underlying Objective-C module 'smart_auth' not found

### ISSUE THREAD

**Issue by jiapan0622** [Tkko/flutter_smart_auth#17]
<img width="1162" alt="sss" src="https://github.com/Tkko/flutter_smart_auth/assets/19727533/922bcc85-c738-4f21-ab63-90d58ef1ed1d">
Xcode15

**Comment by Tkko** [comment]
Hey @jiapan0622, can you provide more details?
Have you tried `pod install` `pod update`?
