### ISSUE TITLE
Dependency 'androidx.core:core-ktx:1.12.0' requires libraries and applications depend on it to compile against version 34 or later of the Android APIs.

### ISSUE THREAD

**Issue by ashu3699** [Tkko/flutter_smart_auth#18]
smart_auth: ^2.0.0

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkReleaseAarMetadata'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
   > 2 issues were found when checking AAR metadata:

       1.  Dependency 'androidx.core:core-ktx:1.12.0' requires libraries and applications that
           depend on it to compile against version 34 or later of the
           Android APIs.

           :app is currently compiled against android-33.

           Also, the maximum recommended compile SDK version for Android Gradle
           plugin 7.4.2 is 33.

           Recommended action: Update this project's version of the Android Gradle
           plugin to one that supports 34, then update this project to use
           compileSdkVerion of at least 34.

           Note that updating a library or application's compileSdkVersion (which
           allows newer APIs to be used) can be done separately from updating
           targetSdkVersion (which opts the app in to new runtime behavior) and
           minSdkVersion (which determines which devices the app can be installed
           on).

       2.  Dependency 'androidx.core:core:1.12.0' requires libraries and applications that
           depend on it to compile against version 34 or later of the
           Android APIs.

           :app is currently compiled against android-33.

           Also, the maximum recommended compile SDK version for Android Gradle
           plugin 7.4.2 is 33.

           Recommended action: Update this project's version of the Android Gradle
           plugin to one that supports 34, then update this project to use
           compileSdkVerion of at least 34.

           Note that updating a library or application's compileSdkVersion (which
           allows newer APIs to be used) can be done separately from updating
           targetSdkVersion (which opts the app in to new runtime behavior) and
           minSdkVersion (which determines which devices the app can be installed
           on).

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 52s

**Comment by mahdinba97** [comment]
could you please mention the version of flutter and android sdk  of your project?

**Comment by ashu3699** [comment]
flutter : 3.16.8 --stable
android: 33

**Comment by mahdinba97** [comment]
It is simply saying you should update your compileSdk at least to 34. It is always recommended to update your compile sdk so you could always continue building your apps for app store. And the latest update right now (PR #16) fixes the problem on sdk 34.

**Comment by ashu3699** [comment]
there are packages which still doesn't support sdk 34, so we have to use 33 till then.
