### ISSUE TITLE
[Q] What are the cases that 'getAppSignature' returns 'N/A'?

### ISSUE THREAD

**Issue by burekas7** [Tkko/flutter_smart_auth#21]
Hi,

I have a general question regarding the 'getAppSignature' function:
What are the cases that 'getAppSignature' returns 'N/A'?

It seems that it mostly happens with iOS. Is it a correct behavior?
Sometimes (rare but still) it happens also in Android, what could be a reason for that?

Thanks.

**Comment by Tkko** [comment]
The `getAppSignature` is only supported on Android and if it's not working on Android in some cases you can checkout this [guide](https://stackoverflow.com/questions/53849023/android-sms-retriever-api-computing-apps-hash-string-problem) to get the signature manually
