### ISSUE TITLE
detect wrong sms code

### ISSUE THREAD

**Issue by Nidhi1396-NP** [Tkko/flutter_smart_auth#26]
**Describe the bug**
Detect Wrong SMS code from sms with templete like this.

OTP for XXXXXX (XX1245) is 811739 (valid for 10 mins).

in SMS code we required 811739 as code. but i got 1245 as code.

**Comment by ImanGhasemiArani** [comment]
hello,
you should write your own pattern for code detection in `matcher` field in `getSmsCode`. (`'\\d{4,8}'` is the default pattern that detect wrong).
